### ISSUE TITLE
parsing bug

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#24]
```css

._19_u :focus { outline: none !important; }
```
is rendered as

```css

._19_u :focus { outline: !important; }
```
