### ISSUE TITLE
incorrectly expand css nesting rules

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#38]
```css
.error, #404 {
 &:hover>.baz {
  color: red
 }
}
```

is expanded as 

```css
.error,#404:hover>.baz {
 color: red
}
```

it should be

```css
:is(.error,#404):hover>.baz {
 color: red
}
```
