### ISSUE TITLE
Invalid escape sequence rendering

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#4]
the '\' is stripped from escape sequeences

```css
@media (max-width: 767px) {.babybear\:z-0 { z-index: 0; }}
```

becomes

```css
@media (max-width: 767px) {.babybear:z-0 { z-index: 0; }}
```
