### ISSUE TITLE
v0.7.0

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#43]
- [x] fix merging rules

```css
.a {
display:none;
}
.b {
display:none;
}
.c {
display:none;
}
```
is incorrectly parsed as 

```css
.b,.c {
display:none;
}
```
- [ ] experimental CSS prefix removal
    - [x] declaration name
    - [ ] declaration value
    - [ ] exclude -webkit-* gradients
    - [x] css selector validation
        - [x] pseudo element
        - [x] partial pseudo class validation. does not validate parameters
        - [x] attribute selector
        - [x] combinator
        - [x] simple selector
        - [x] nested selector
        - [x] strict vs permissive validation: allow unknown items such as pseudo classes
            - [x] allow unknown pseudo classes
            - [x] allow unknown attribute selectors
- [x] strip universal selector when possible
