### ISSUE TITLE
incorrectly expand css nesting rules

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#45]
```css
.s {
 [type=text],[type=text i],[type=text s],[type=text i]+b,&:focus {
  --animate-duration: 1s
 }
```
the result is incorrect

```javascript
parse(file, {
                minify: true, nestingRules: true, validation: true
            }).then(result => expect(render(result.ast, {minify: false, expandNestingRules: true}).code)
```
