### ISSUE TITLE
incorrectly replace nesting rule

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#57]
input css

```css

.card {
  inline-size: 40ch;
  aspect-ratio: 3/4;

  @scope (&) {
    :scope {
      border: 1px solid white;
    }
  }
}
```

result

```css
.parent {
 color: blue
}
@scope (.parent >.scope) to (.parent .limit) {
 & .content {
  color: red
 }
}
```

expected result

```css
.card {
 inline-size: 40ch;
 aspect-ratio: 3/4
}
@scope (.card) {
 :scope {
  border: 1px solid #fff
 }
}
```
