### ISSUE TITLE
Invalid shorthand generation

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#6]
this css is incorrectly parsed

```css
@media all {
    html {
        font-family: Blanco, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        font-size: clamp(12px, 0.8rem + 0.25vw, 20px);
        font-weight: 400;
        line-height: 1.7;
    }
}

button.jetpack-instant-search__overlay-close {
    align-items: center;
    appearance: none;
    background-image: none;
    background-position: initial;
    background-size: initial;
    background-repeat: initial;
    background-attachment: initial;
    background-origin: initial;
    background-clip: initial;
    border-top: none;
    border-right: none;
    border-left: none;
    border-image: initial;
    border-bottom: 1px solid rgb(230, 241, 245);
    border-radius: 0px;
    box-shadow: none;
    cursor: pointer;
    display: flex;
    height: 61px;
    justify-content: center;
    line-height: 1;
    margin: 0px;
    outline: none;
    padding: 0px;
    text-decoration: none;
    text-shadow: none;
    text-transform: none;
    width: 60px;
    background-color: transparent !important;
}
```
