### ISSUE TITLE
current color handling

### ISSUE THREAD

**Issue by tbela99** [tbela99/css-parser#78]
current color is not parsed correctly

```css
 
  .from {
    color: color-mix(in lab, oklch(from currentColor l c calc(h/2) ) 80%, #f00 50%);
}

```
